CREATE TABLE IF NOT EXISTS REPORT
(
    REP_NO  INT AUTO_INCREMENT PRIMARY KEY COMMENT '신고번호',
    REP_TITLE VARCHAR(120) NOT NULL COMMENT '신고제목',
    REP_CONTENT TEXT NOT NULL COMMENT '신고내용', -- 데이터 타입 변경
    REP_DATE DATE NOT NULL COMMENT '신고일', -- 데이터 타입 변경
    REP_ID VARCHAR(15) NOT NULL COMMENT '신고아이디',
    REP_PRC VARCHAR(4) NOT NULL COMMENT '신고처리여부'
    ) ENGINE=INNODB COMMENT '신고';


