spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: dbc:mysql://localhost/jdbctest
    username: ohgiraffers
    password: ohgiraffers

mybatis:
  mapper-locations: mappers/**/*.xml